name = "PostForecasts"
uuid = "b2f9963d-2794-4afd-bb03-e604c489c349"
version = "0.1.2"
authors = ["lipiecki <arkadiusz.lipiecki@pwr.edu.pl>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Combinatorics = "1.0.2"
DelimitedFiles = "1.9.1"
Documenter = "1.8.1"
ForwardDiff = "1.3.0"
HDF5 = "0.17.2"
HiGHS = "1.13.0"
JuMP = "1.24.0"
LinearAlgebra = "1.10.0"
NLopt = "1.2.1"
SpecialFunctions = "2.5.0"
Statistics = "1.10.0"
Test = "1.10.0"
julia = "1.10.0"
